if !exists('g:polyglot_disabled') || index(g:polyglot_disabled, 'nginx') == -1
  
" Phusion Passenger Module <https://www.phusionpassenger.com/library/config/nginx/>
" Passenger is an open source web application server.
syn keyword ngxDirectiveThirdParty passenger_root
syn keyword ngxDirectiveThirdParty passenger_enabled
syn keyword ngxDirectiveThirdParty passenger_base_uri
syn keyword ngxDirectiveThirdParty passenger_document_root
syn keyword ngxDirectiveThirdParty passenger_ruby
syn keyword ngxDirectiveThirdParty passenger_python
syn keyword ngxDirectiveThirdParty passenger_nodejs
syn keyword ngxDirectiveThirdParty passenger_meteor_app_settings
syn keyword ngxDirectiveThirdParty passenger_app_env
syn keyword ngxDirectiveThirdParty passenger_app_root
syn keyword ngxDirectiveThirdParty passenger_app_group_name
syn keyword ngxDirectiveThirdParty passenger_app_type
syn keyword ngxDirectiveThirdParty passenger_startup_file
syn keyword ngxDirectiveThirdParty passenger_restart_dir
syn keyword ngxDirectiveThirdParty passenger_spawn_method
syn keyword ngxDirectiveThirdParty passenger_env_var
syn keyword ngxDirectiveThirdParty passenger_load_shell_envvars
syn keyword ngxDirectiveThirdParty passenger_rolling_restarts
syn keyword ngxDirectiveThirdParty passenger_resist_deployment_errors
syn keyword ngxDirectiveThirdParty passenger_user_switching
syn keyword ngxDirectiveThirdParty passenger_user
syn keyword ngxDirectiveThirdParty passenger_group
syn keyword ngxDirectiveThirdParty passenger_default_user
syn keyword ngxDirectiveThirdParty passenger_default_group
syn keyword ngxDirectiveThirdParty passenger_show_version_in_header
syn keyword ngxDirectiveThirdParty passenger_friendly_error_pages
syn keyword ngxDirectiveThirdParty passenger_disable_security_update_check
syn keyword ngxDirectiveThirdParty passenger_security_update_check_proxy
syn keyword ngxDirectiveThirdParty passenger_max_pool_size
syn keyword ngxDirectiveThirdParty passenger_min_instances
syn keyword ngxDirectiveThirdParty passenger_max_instances
syn keyword ngxDirectiveThirdParty passenger_max_instances_per_app
syn keyword ngxDirectiveThirdParty passenger_pool_idle_time
syn keyword ngxDirectiveThirdParty passenger_max_preloader_idle_time
syn keyword ngxDirectiveThirdParty passenger_force_max_concurrent_requests_per_process
syn keyword ngxDirectiveThirdParty passenger_start_timeout
syn keyword ngxDirectiveThirdParty passenger_concurrency_model
syn keyword ngxDirectiveThirdParty passenger_thread_count
syn keyword ngxDirectiveThirdParty passenger_max_requests
syn keyword ngxDirectiveThirdParty passenger_max_request_time
syn keyword ngxDirectiveThirdParty passenger_memory_limit
syn keyword ngxDirectiveThirdParty passenger_stat_throttle_rate
syn keyword ngxDirectiveThirdParty passenger_core_file_descriptor_ulimit
syn keyword ngxDirectiveThirdParty passenger_app_file_descriptor_ulimit
syn keyword ngxDirectiveThirdParty passenger_pre_start
syn keyword ngxDirectiveThirdParty passenger_set_header
syn keyword ngxDirectiveThirdParty passenger_max_request_queue_size
syn keyword ngxDirectiveThirdParty passenger_request_queue_overflow_status_code
syn keyword ngxDirectiveThirdParty passenger_sticky_sessions
syn keyword ngxDirectiveThirdParty passenger_sticky_sessions_cookie_name
syn keyword ngxDirectiveThirdParty passenger_abort_websockets_on_process_shutdown
syn keyword ngxDirectiveThirdParty passenger_ignore_client_abort
syn keyword ngxDirectiveThirdParty passenger_intercept_errors
syn keyword ngxDirectiveThirdParty passenger_pass_header
syn keyword ngxDirectiveThirdParty passenger_ignore_headers
syn keyword ngxDirectiveThirdParty passenger_headers_hash_bucket_size
syn keyword ngxDirectiveThirdParty passenger_headers_hash_max_size
syn keyword ngxDirectiveThirdParty passenger_buffer_response
syn keyword ngxDirectiveThirdParty passenger_response_buffer_high_watermark
syn keyword ngxDirectiveThirdParty passenger_buffer_size, passenger_buffers, passenger_busy_buffers_size
syn keyword ngxDirectiveThirdParty passenger_socket_backlog
syn keyword ngxDirectiveThirdParty passenger_log_level
syn keyword ngxDirectiveThirdParty passenger_log_file
syn keyword ngxDirectiveThirdParty passenger_file_descriptor_log_file
syn keyword ngxDirectiveThirdParty passenger_debugger
syn keyword ngxDirectiveThirdParty passenger_instance_registry_dir
syn keyword ngxDirectiveThirdParty passenger_data_buffer_dir
syn keyword ngxDirectiveThirdParty passenger_fly_with
syn keyword ngxDirectiveThirdParty union_station_support
syn keyword ngxDirectiveThirdParty union_station_key
syn keyword ngxDirectiveThirdParty union_station_proxy_address
syn keyword ngxDirectiveThirdParty union_station_filter
syn keyword ngxDirectiveThirdParty union_station_gateway_address
syn keyword ngxDirectiveThirdParty union_station_gateway_port
syn keyword ngxDirectiveThirdParty union_station_gateway_cert
syn keyword ngxDirectiveDeprecated rails_spawn_method
syn keyword ngxDirectiveDeprecated passenger_debug_log_file


endif
