if !exists('g:polyglot_disabled') || index(g:polyglot_disabled, 'nginx') == -1
  
" Video Thumbextractor Module <https://github.com/wandenberg/nginx-video-thumbextractor-module>
" Extract thumbs from a video file
syn keyword ngxDirectiveThirdParty video_thumbextractor
syn keyword ngxDirectiveThirdParty video_thumbextractor_video_filename
syn keyword ngxDirectiveThirdParty video_thumbextractor_video_second
syn keyword ngxDirectiveThirdParty video_thumbextractor_image_width
syn keyword ngxDirectiveThirdParty video_thumbextractor_image_height
syn keyword ngxDirectiveThirdParty video_thumbextractor_only_keyframe
syn keyword ngxDirectiveThirdParty video_thumbextractor_next_time
syn keyword ngxDirectiveThirdParty video_thumbextractor_tile_rows
syn keyword ngxDirectiveThirdParty video_thumbextractor_tile_cols
syn keyword ngxDirectiveThirdParty video_thumbextractor_tile_max_rows
syn keyword ngxDirectiveThirdParty video_thumbextractor_tile_max_cols
syn keyword ngxDirectiveThirdParty video_thumbextractor_tile_sample_interval
syn keyword ngxDirectiveThirdParty video_thumbextractor_tile_color
syn keyword ngxDirectiveThirdParty video_thumbextractor_tile_margin
syn keyword ngxDirectiveThirdParty video_thumbextractor_tile_padding
syn keyword ngxDirectiveThirdParty video_thumbextractor_threads
syn keyword ngxDirectiveThirdParty video_thumbextractor_processes_per_worker


endif
