if polyglot#init#is_disabled(expand('<sfile>:p'), 'typescript', 'syntax/yats/web-blob.vim')
  finish
endif

syntax keyword typescriptGlobal containedin=typescriptIdentifierName Blob BlobBuilder
syntax keyword typescriptGlobal containedin=typescriptIdentifierName File FileReader
syntax keyword typescriptGlobal containedin=typescriptIdentifierName FileReaderSync
syntax keyword typescriptGlobal containedin=typescriptIdentifierName URL nextgroup=typescriptGlobalURLDot,typescriptFuncCallArg
syntax match   typescriptGlobalURLDot /\./ contained nextgroup=typescriptURLStaticMethod,typescriptProp
syntax keyword typescriptGlobal containedin=typescriptIdentifierName URLUtils
syntax keyword typescriptFileMethod contained readAsArrayBuffer readAsBinaryString nextgroup=typescriptFuncCallArg
syntax keyword typescriptFileMethod contained readAsDataURL readAsText nextgroup=typescriptFuncCallArg
syntax cluster props add=typescriptFileMethod
hi def link typescriptFileMethod Keyword
syntax keyword typescriptFileReaderProp contained error readyState result
syntax cluster props add=typescriptFileReaderProp
hi def link typescriptFileReaderProp Keyword
syntax keyword typescriptFileReaderMethod contained abort readAsArrayBuffer readAsBinaryString nextgroup=typescriptFuncCallArg
syntax keyword typescriptFileReaderMethod contained readAsDataURL readAsText nextgroup=typescriptFuncCallArg
syntax cluster props add=typescriptFileReaderMethod
hi def link typescriptFileReaderMethod Keyword
syntax keyword typescriptFileListMethod contained item nextgroup=typescriptFuncCallArg
syntax cluster props add=typescriptFileListMethod
hi def link typescriptFileListMethod Keyword
syntax keyword typescriptBlobMethod contained append getBlob getFile nextgroup=typescriptFuncCallArg
syntax cluster props add=typescriptBlobMethod
hi def link typescriptBlobMethod Keyword
syntax keyword typescriptURLUtilsProp contained hash host hostname href origin password
syntax keyword typescriptURLUtilsProp contained pathname port protocol search searchParams
syntax keyword typescriptURLUtilsProp contained username
syntax cluster props add=typescriptURLUtilsProp
hi def link typescriptURLUtilsProp Keyword
syntax keyword typescriptURLStaticMethod contained createObjectURL revokeObjectURL nextgroup=typescriptFuncCallArg
hi def link typescriptURLStaticMethod Keyword
